Gemfile
Gemfile.lock
README.md
Rakefile
spec/javascripts/support/jasmine.yml

We're keen to do some testing of the JavaScript bits and bobs in this
project, and subsequently need a test framework to do so. Jasmine
appears to be the weapon of choice in other parts of GDS (including the
service manual), so it makes sense to use it here, too.
This adds a very basic Jasmine configuration that we can write some
tests on top of.

Add Jasmine for JS testing

---

source/stylesheets/modules/_app-pane.scss

The header is not appearing and neither the body nor the table of contents are scrollable in Firefox.
This fixes that by adding a min-height: 0; declaration to the `.app-pane__body` element. Apparently:
“Flex items establish a default minimum size that's based on their children's intrinsic size (which doesn't consider "overflow" properties on their children/descendants).”
“Whenever you've got an element with overflow: [hidden|scroll|auto] inside of a flex item, you need to give its ancestor flex item min-width:0 (in a horizontal flex container) or min-height:0 (in a vertical flex container), to disable this min-sizing behavior, or else the flex item will refuse to shrink smaller than the child's min-content size.” [1] [2]
[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1043520
[2]: …

Fix documentation layout in Firefox

---

source/layouts/layout.erb

Add labels to distinguish the two navigation elements, add a `main` element to allow the user to easily switch between the table of contents and the documentation body using landmarks.

Accessibility improvements

---

.gitignore
script/deploy

This adds an extremely basic script at `script/deploy` that pushes the
site to integration on PaaS, along with a few pre-flight checks:
- It ensures we have a Staticfile.auth file present, which is required
to give us basic authentication on PaaS
- Checks we're on master
- Checks our working tree isn't dirty (in English: checks we have no
files that aren't commited into git that would be built)
- Checks that our branch is up-to-date

Add deployment script

---

source/stylesheets/modules/_technical-documentation.scss

At the moment, an image inserted into the tech docs will be rendered at
whatever resolution it's supplied in. This is somewhat far from ideal,
as a massive image could end up breaking the page in unpleasant ways.
This adds a max-width of 100% to all images inside the technical
documentation container to ensure we stop anything overflowing it.
Before:
After:

Add a max-width to images

---

manifest.yml
script/deploy

It seems advisable to supply a manifest.yml file to be used by
CloudFoundry rather than passing parameters into `cf push` – this way,
if someone runs the push command without running `script/deploy`, things
won't explode in a surprising fashion.
More info:
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html

Add CloudFoundry manifest.yml

---

config.rb
lib/tech_docs_html_renderer.rb

It might be nice for us to automatically wrap images in a link, so if
they're shrunk for whatever reason they can be clicked on to show a
full-resolution version. This does just that.
There's not an option built in to Redcarpet which allows us to do this,
so this adds a custom Redcarpet renderer which wraps up images in an <a>
tag.

Automatically linkify images

---

script/deploy

This updates our deployment script's dirty working tree check to ensure
it always returns a zero exit code – if it doesn't, the script crashes
out prematurely.

Improve dirty working tree check

---

config.rb
source/layouts/layout.erb

This adds a <link rel="canonical" /> tag to the <head> of the document
for SEO purposes, and a config option (`host`) to allow the canonical
host to be set.

Add canonical link tag

---

config.rb
lib/tech_docs_html_renderer.rb

When passing a `renderer` argument to `set :markdown`, Middleman bins
all the other options you pass into it.
This isn't particularly helpful, so this sets the options in the custom
renderer class instead.

Fix custom renderer

---

source/stylesheets/modules/_app-pane.scss

IE8 through IE10 don’t support flexbox, so fall back to a simpler layout with the navigation floated to the left.
We discussed moving away from flexbox to just using absolutely positioned divs to define the application layout, but it would require us to ‘know’ and fix the the size of the header. Given the header currently ‘breaks’ onto two lines for the Platform as a Service documentation, this won’t really work for us.
We are making an assumption that IE8-IE10 will account for a even lower percentage of users than we see on GOV.UK (~2.75%) as they will be from a more technical background. We should validate this once we have collected analytics data in production.

Fix layout in IE8 through IE10

---

nginx.conf
script/deploy

This adds a custom nginx configuration, which is based on the [CloudFoundry static buildpack's default one](https://github.com/cloudfoundry/staticfile-buildpack/blob/bd7a288e11b27f1c5095d62bcd09780a14c5151e/conf/nginx.conf), which forces a 301 redirect to the "canonical" URL of the website if the supplied Host header is anything over than paas-tech-docs-integration.cloudapps.digital.

Add custom nginx.conf

---

config.rb

These are not related to rendering, and therefore should not be passed
into the markdown renderer, but the markdown parser.

Fix fenced code blocks

---

source/layouts/layout.erb

In an ideal world the `<ul>` can be simply generated by the table of contents helper, and this means we don’t want to e.g. add classes to it.
Those classes would be just as happy living on the parent `<nav>` element, and this also fixes the fact that two elements have the `#toc` id. Whoops.

Fix duplicated use of ‘#toc’ id, move classes to nav

---

Gemfile
Gemfile.lock
config.rb
source/documentation/deploying_apps/deploying_django.md
source/documentation/deploying_apps/deploying_node_js.md
source/documentation/deploying_apps/deploying_rails.md
source/documentation/deploying_apps/deploying_static_sites.md
source/documentation/index.md
source/index.html.md.erb
source/stylesheets/_core.scss
source/stylesheets/_syntax-highlighting.scss
source/stylesheets/modules/_technical-documentation.scss
source/stylesheets/palette/syntax-highlighting.scss

Use the middleman-syntax gem to automatically highlight blocks of code using [Rouge][1].
The HTML output that rouge creates is compatible with the python syntax highlighter ‘Pygments’. In order to ensure that the highlighting makes sense we build on top of [Base 16][2] to map pygments to a palette of sixteen colours.
The palette is then based loosely on both the GitHub colour palette and work that @edwardhorsford did, ensuring that all combinations meet colour contrast standards. Ed is still tweaking the palette but we need to start using this today, so another PR will likely follow with those tweaks.
[1]: https://github.com/jneen/rouge
[2]: https://github.com/chriskempson/base16

Syntax Highlighting for Code Blocks

---

config.rb
config/tech-docs.yml
source/layouts/layout.erb

In an attempt to make the 'templatization' of this project a bit easier,
this adds a configuration hash in `config.rb` to set some options that
are likely to change between projects.
I'm not entirely convinced by the header links being in here – it does
nicely abstract them away from the actual HTML, but open to better
alternatives.

Add some basic configuration options

---

source/stylesheets/modules/_anchored-heading.scss
source/stylesheets/modules/_govuk-logo.scss
source/stylesheets/modules/_toc.scss

This will output as if `image-url` is used in most cases, but will allow other projects consuming this to override `$path` to specify the location of their image assets.
Fixes #35

Use file-url helper from frontend toolkit

---

lib/tech_docs_html_renderer.rb

We're using target="_blank" to open images in a new window. There are known issues with being able to exploit such links using `window.opener' (https://mathiasbynens.github.io/rel-noopener/)
Whilst the images are *probably* going to be hosted within the same repo and under our control, we can't really guarantee it. Adding rel="noopener" is not detrimental, so let's play it safe.

Add rel="noopener" when linking to images

---

source/stylesheets/modules/_toc.scss

Making it 19px instead of 16px (on desktop) makes the hierachy clearer.

Increase font size of level 1 in table of contents

---

source/javascripts/modules/table-of-contents.js
source/stylesheets/modules/_toc.scss

By default when the table of contents is at the top or bottom, scrolling in that direction will scroll the body 'behind' the table of contents. Fix this by preventing ever reaching the top or bottom of the table of contents (by 1 pixel) using javascript [1]. Non-JS users will just experience the (slightly) funky scrolling behaviour.
[1]: http://blog.christoffer.me/six-things-i-learnt-about-ios-safaris-rubber-band-scrolling/

Fix rubber banding in iOS.

---

config.rb
lib/tech_docs_html_renderer.rb
source/stylesheets/modules/_technical-documentation.scss

Enable table support in Redcarpet, wrap the table with a container so that we can make it ‘scroll’ on mobile, and add basic styling (copied from Whitehall)

Add support and basic styling for tables

---

Thorfile

As these are only supported by Ruby 2.3 and above (which our tech
writers are unlikely to be using), replace them with non-squiggly
heredocs and accept that the indentation is going to be a bit weird.

Stop using squiggly heredocs in Thorfile

---

README.md

It took me 5 minutes to figure out I had accidentally copy-pasted the trailing dot, causing the command to fail.

Make update command copy-pasteable

---

template/source/layouts/header_footer_only.erb
template/source/layouts/layout.erb

This separates a common layout (with header, footer, stylesheet and javascript includes) from the tech-docs layout (table of contents and content).
It allows users to generate pages with a different way of building the table of contents (or none at all).
Primary use case is the alphagov/govuk-developers project, which generates a [custom table of contents](https://github.com/alphagov/govuk-developers/blob/7812aedae055605b31590eec4f5bbc125ed0117c/source/index.html.erb#L9-L26).
I've also considered flipping the naming of the templates, so that `layout.erb` is the base template, and the tech docs layout is the special case. You can see it in this branch: 
https://github.com/alphagov/tech-docs-template/compare/layout-alt-option
That option has my preference, but it does introduce a new config …

Create a generic layout to use

---

optional/config/tech-docs.yml.tt
template/source/layouts/header_footer_only.erb

This adds a GA snippet, and a config option (`ga_tracking_id`) which
allows us to get information about site usage through GA.

Add Google Analytics

---

.travis.yml
README.md
Thorfile
create-test-site.sh

In #50 I introduced a bug in the template by using `layout` instead of `wrap_layout`.
This commit adds steps to the test run on Travis to generate an example site. This would've caught the bug before merging.

Create site on CI to make sure template builds correctly

---

optional/config/tech-docs.yml.tt
template/Gemfile
template/source/layouts/layout.erb

There's a desire to be able to set a maximum heading level to include in
the left-hand table of contents – this is implemented in the
table_of_contents gem (see alphagov/table_of_contents#4), and is now
configurable here via the `max_toc_heading_level` option.

Add configurable ToC max heading level

---

template/source/javascripts/modules/in-page-navigation.js

If the user navigates within the page before they scroll, the scroll position will not be recorded in their history state object so clicking the back button will not take them back to the top of the page as they might expect it to.
We can work around this by scrolling to the top of the page when an empty state is popped from the history api.

Fix scroll history bug

---

template/source/layouts/header_footer_only.erb

“The label is "Top level navigation", which means that screen readers announce something like "Top level navigation navigation". They identify the fact it's a navigation region because of the <nav> and/or role="navigation, so there is no need to include the word "navigation" in the label.”
(Thanks, Léonie)

Fix ARIA label for top level nav

---

template/source/javascripts/modules/in-page-navigation.js

The previous solution worked in Chrome, but Firefox and Safari fire pop state events when a anchor link is clicked, which means you can’t use the navigation. At all. Oops.
Instead of assuming that when there is no scrollTop stored we should scroll to the top, explicitly store the scroll position on page load if no existing state is present. Also allow restoreScrollPosition to scroll to the top as a value of 0 for scrollTop would be falsey.

Store initial scroll state on page load

---

template/source/javascripts/analytics.js
template/source/javascripts/application.js

This adds some fairly rudimentary Google Analytics event tracking to the
template. It allows us to track clicks on links in the header, table of
contents and inside the generated markdown.
The events used are per this Trello card:
https://trello.com/c/oI9DMxao/479-analytics

Add GA event tracking

---

template/source/javascripts/modules/in-page-navigation.js

This adds some functionality to ensure we always have the active ToC
item in view when scrolling through the content pane, by scrolling the
ToC pane in sync with the content pane.
Additionally, it reduces the debounce timeout to 100ms, as 250ms makes
the scrolling appear a tad jerky.

Automatically scroll to active ToC link

---

template/source/javascripts/modules/in-page-navigation.js

The call to handleScrollEvent was previously causing the browser to jump back up to the start of the document. This seems to be because:
1) handleScrollEvent is called _before_ the browser has scrolled the user to the target heading
2) tocItemForFirstElementInView therefore returns the first heading on the page
3) the current history state is therefore updated with the hash of the first heading on the page
4) this appears to be enough to cause the browser to scroll back to the top of the document
We need slightly different behaviour when loading the page for the first time - if there is an anchor specified, we should use the hash and offset for that entry rather than trying to find the first element in view. We’ll fall back to the first element if there is no hash, or the hash does not …

Fix initial page position when linking to anchor

---

template/source/stylesheets/modules/_toc.scss

At the moment, the ToC navigation "jumps" when transitioning to a
highlighted state as the bold version of the text is narrower than the
non-bold version. This fixes that, by reducing the letter-spacing to
ensure things are more consistent.

Improve letter-spacing on ToC items

---

template/source/javascripts/modules/in-page-navigation.js

If a max table of contents level is set in `config.yml`, anchor links to
headings that aren't shown in the table of contents are broken, as our
in-page navigation scroll handling assumes that all headings are linked
to from the ToC.
This adjusts that logic to base scroll handling around the URL fragment,
rather than a list of anchors.

Fix anchor linking when setting a max ToC level

---

optional/config/tech-docs.yml.tt
template/source/layouts/header_footer_only.erb

This is currently being manually added to the PaaS docs which makes upgrading difficult.

Add config to prevent indexing of docs

---

template/source/javascripts/modules/anchored-headings.js
template/source/stylesheets/modules/_anchored-heading.scss

When Google decides to use the h1 of the document, it’s extracting ‘Link to here’ as part of the heading and including it in the title of the page in search results.
Remove ‘Link to here’ as it’s hidden from screen readers anyway, and users of assisted tech would be able to ‘create’ links to individual headings using the table of contents.
Fixes #85

Remove text from anchor links

---

template/Gemfile

Minor update to address some problems which we ran across in building sites created using this template - internal proxies and also some security issues highlighted in http://bundler.io/v1.14/git.html#security.

Update of bundler :github shortcut to use :git and https:// instead of git://

---

README.md
Thorfile

This makes some changes to our `Thorfile` to ensure that we only prompt the user about files that they've actually changed rather than files that have changed in the template.
We do this by:
- Storing the last used template version in a `.template_version` file
- Cloning the last template
- Removing files from the local installation that are the same as the template
- Applying the latest version of the template
This means that the user won't be prompted for files that have updated in the template but they haven't changed locally.

Only diff changed files when updating template

---

template/source/javascripts/modules/in-page-navigation.js

On mobile, we sometimes (?) don’t find any of the possible targets to be at the top of the screen, because their offset is the top of the page and there is a header between the first target and that.
Guarding to allow for result being nil fixes this. It means we don’t update the hash or the nav when the page first loads, but in the mobile viewport that’s not something we do as the user scrolls anyway.

Guard against no heading being seen as active

---

template/source/stylesheets/modules/_technical-documentation.scss

This removes some extra padding which otherwise ends up ‘indenting’ the first line of a multi line code block by 3px.

Remove extra padding from multi line code blocks

---

template/source/stylesheets/modules/_toc.scss

Rather than emboldening the active element, we highlight it with a light grey background and add a five pixel left hand border in the active link colour. This makes the highlighting more obvious, and allows us to do away with the letter-spacing ‘hack’ which was trying to prevent items reflowing when they became bold.
Unfortunately because each item in the table of contents now needs to effectively act as a block of the same size, we can no longer rely on the nested nature of the lists. Instead we have to define the behaviour for each level individually. We’ve implemented indentation for the first six levels of navigation. In a real world situation this number of levels are unlikely to be exposed, but given we have to choose a number of levels to support, matching the h1…h6 elements makes …

Revise highlight state for table of contents

---

template/source/stylesheets/modules/_technical-documentation.scss

The publishing docs use monospaced headings for listing the endpoints available in API docs. This changes `<code>` elements within headings so that they look more like the headings in terms of font size, colour and the lack of background.
Fixes #97

Support monospace headings

---

template/source/stylesheets/modules/_technical-documentation.scss

This removes some extra padding which otherwise ends up ‘indenting’ the first line of a multi line code block by 3px.
This was previously done in d5518b7 but was accidentally reverted as part of 53ac7c7.
:man_facepalming:

Remove extra padding from multi line code blocks (regression)

---

template/config.rb

This makes the assets a bit smaller. One of the recommendations from the PageSpeed extension in Chrome.
https://trello.com/c/jAA7b1pr

Turn on JS/CSS minification

---

template/source/layouts/_analytics.erb

This follows the configuration we use on GOV.UK to anonymise IP addresses and disable advert tracking: https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/analytics/google-analytics-universal-tracker.js#L13-L21

Configure GA tracking options

---

template/source/layouts/_analytics.erb

Set commands should be added to the command queue after the create tracker command.
To avoid missing hits in GA when a document unloads, set the tracker to use the Navigator.sendBeacon() transport mechanism when available.  This will transmit hits to GA asynchronously when the User Agent has an opportunity to do so, without delaying the unload or affecting the performance of the next navigation.  GA will fallback to XMLHttpRequest or Image transport mechanisms when navigator.sendBeacon isn't supported by the user's browser.
See:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon
https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits#specifying_different_transport_mechanisms

Correct configuration for GA

---

template/source/stylesheets/modules/_technical-documentation.scss

These were removed in #95.
We (the PaaS team) have seen users getting confused by the one-page
layout in research. We therefore think that removing these dividing
lines is only going to exacerbate this.
Before:
After:

Re-add the dividing lines between H1 sections.

---

template/source/stylesheets/modules/_app-pane.scss

This causes the layout to fallback to the non-flexbox version when javascript is disabled.
We use Modernizr to sniff for Flexbox support because IE11 supports flexbox but does not support feature queries, and at the time this was done we believed that IE11 users would outnumber non-js users.
Fixes #119

Use non-flexbox layout for non-js layout

---

optional/source/documentation/index.md

This adds a markdown table to the example page to illustrate how to generate a table.
Closes #138 & #139.

Add markdown table to example

---

optional/README.md

This adds docs for creating a separate HTML page, outside of the single page documentation.
Should help with https://github.com/alphagov/tech-docs-template/issues/128.

Add documentation on how to create extra pages

---

Gemfile
Gemfile.lock
README.md

Since this is a Middleman template, developers working on the template itself have to create a new site to test changes.
This adds middleman to the Gemfile (so all dependencies are installed) and updates the instructions.
This PR is best reviewed by trying out the new instructions and confirming a new static site is generated.

Improve instructions for local development

---

Thorfile
optional/script/deploy

In the gds-way repo we're deploying tech docs from Travis (not sure how common this is) our configuration to do that is in .[travis.yml](https://github.com/alphagov/gds-way/blob/master/.travis.yml) with no need to call a separate deploy script. In setting this up we missed the step to copy nginx configuration, it seems easier to have middleman copy over the file. This PR moves the file into source which makes middleman include it in the build folder.
A question for a separate PR could be if we should be recommending the .travis.yml configuration rather than including the deploy script?

Move nginx.conf into source

---

README.md

This lists the active users of the tech-docs-template that I've found. The purpose of the list is to provide examples and to create more of a community.
The list is probably not exhaustive.

List active users of the template

---

README.md

This has changed since https://github.com/alphagov/tech-docs-template/pull/144.

Update instructions on updating the template

---

README.md

- The GOV.UK Notify project GitHub repo wasn’t in brackets and it looked weird compared to the others.

Put the “GitHub repo” link for projects consistently in brackets

---

optional/config/tech-docs.yml.tt
template/Gemfile

See: alphagov/tech-docs-gem#28

GTD-1: Added search option to template

---

template/Gemfile

We should be using `https` for gem locations, not `git`.

Use https for gem definitions

---

Thorfile
optional/manifest.yml.tt

A production app should always use more than 1 instance on the PaaS,
otherwise there will be the potential for downtime when changes to the
platform are being deployed.
Also fix the branding when asking about the PaaS.

Deploy 2 instances when deploying to PaaS

---

template/Gemfile

The latest version of tech-docs-gem now points to gds-middleman-search
directly.
See https://github.com/alphagov/tech-docs-template/pull/175

Remove fork from template Gemfile

---

README.md

Simply removing a typo from the README

Remove superfluous backtick from README example

---

.travis.yml

Update Ruby to 2.6.6 to fix the build issues in for example https://github.com/alphagov/tech-docs-template/pull/195.

Update ruby to 2.6.6

---

README.md

Replace readme content with links to TDT documentation. This means that this readme stays aligned with the TDT documentation.

Replace readme content with links to TDT documentation

---

optional/config/tech-docs.yml.tt

This updates the template for the `tech-docs.yml` file, to ensure that a base Tech Docs Template instance does not have 2 duplicate links to the same place (the `service_link` link and the `about` link) - which was causing accessibility issues.

Remove duplicate header link

---

template/Gemfile

This change enables the generation of sites using tech-docs-template on 64-bit Windows

Add support for 64-bit Windows to gem dependencies

---

.travis.yml

Travis CI is currently defaulting to using Node.js v8.x.x because the Travis config file does not specify to use Node at all.
However a version of Node greater than 10 is needed for this repo, because the tech-docs-gem uses it, so Travis builds are failing across the board.
This PR uses [nvm](https://github.com/nvm-sh/nvm) to make sure that the version of Node used for tests is the latest version of the current long term support (LTS) series.

Fix failing Travis builds

---

optional/config/tech-docs.yml.tt
optional/script/deploy

We've renamed the default branch to main, following best practice on GitHub [[1]], and we want and expect that users will do the same. This is especially the case for new repositories on GitHub, which will have the name 'main' instead of 'master'.
This PR updates the example deploy script to match.
We also add the new default branch name to the config template. This is because in the [tech-docs-gem](github.com/alphagov/tech-docs-gem) we assume the default branch is named 'master', and changing that would be a breaking change. By changing it here we can immediately reach new users of the tech docs template (without affecting our ability to make the breaking change), and it also keeps the example deploy script and the build output consistent.
[1]: https://github.com/github/renaming

Rename default branch to 'main'

---

optional/README.md

Links in the template README to Ruby and Middleman installations.
(There's likely scope to identifying dead links here, somehow, but that's not part of this PR.)
As a developer not familiar with Ruby/Middleman, I need working links to the installation instructions

Fix links to Ruby/Middleman docs
